BATT_OUTDATED := if `brew outdated -q | grep batt | wc -l` == '0' { "true" } else { "false" }

# List recipe
help:
  just --list

# Find and preview
find-n-preview:
  fzf --preview "bat --color=always {}"
  # Useful env var
  # export FZF_DEFAULT_OPTS="--preview 'bat --color=always {}'"

# Show outdated packages
brew-list-outdated: brew-update
  brew outdated -q
  brew outdated -q --cask --greedy

# Update brew repos
brew-update:
  brew update

# Upgrade brew packages
brew-upgrade: brew-update
  # Adding `-` before a command ignores exit code 1 (false).
  -{{BATT_OUTDATED}} && sudo brew services stop batt
  brew upgrade
  brew upgrade --cask --greedy
  -{{BATT_OUTDATED}} && sudo brew services start batt
  #sudo batt status

# Fix brew permission issue
brew-fix-permission:
  sudo chown -R ${whoami} ${brew --prefix}
  sudo chown -R ${whoami} ${HOME}/Library/Caches/Homebrew/bootsnap

