
# List recipe
help:
  just --list

# Find and preview
find-n-preview:
  fzf --preview "bat --color=always {}"
  # Useful env var
  # export FZF_DEFAULT_OPTS="--preview 'bat --color=always {}'"

# Show outdated packages
brew-list-outdated: brew-update
  brew outdated
  brew outdated --cask --greedy

# Update brew repos
brew-update:
  brew update

# Upgrade brew packages
brew-upgrade: brew-update
  # Adding `-` before a command ignores exit code 0.
  # `grep` returns 0 if `batt` is not found in outdated package list.
  -just brew-list-outdated | grep batt && sudo brew services stop batt
  brew upgrade
  brew upgrade --cask --greedy
  -just brew-list-outdated | grep batt && sudo brew services start batt

